apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-deployment
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers: 
        - name: adcontainer
          image: clahandevops/user:latest
          ports:
            - containerPort: 80
          env: 
            - name: TITLE
              value: "WELCOME TO LOGIN USER"
---
apiVersion: v1
kind: Service
metadata:
  name: add-svc
spec: 
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: my-app

