apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice-deployment
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: httpd-app
  template:
    metadata:
      labels:
        app: httpd-app
    spec:
      containers: 
        - name: cartservice-container
          image: httpd
          ports:
            - containerPort: 80
          env: 
            - name: TITLE
              value: "APACHE-APP2"
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-cartsvc
spec:
  selector:
    app: httpd-app
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP

